version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database
    environment:
      - DATABASE_URL=sqlite:///database/app.db
    restart: unless-stopped
    container_name: executiva_cloud_app
